apiVersion: apps/v1
kind: Deployment
metadata:
  name: abc_tech-deploy
spec:
  selector:
    matchLabels:
      app: abc_tech-deploy
  replicas: 3
  template:
    metadata:
      labels:
        app: abc_tech-deploy
    spec:
      containers:
      - name: abc-app
        image: polo5172/abc_tech:latest
        ports:
        - containerPort: 8080

             