apiVersion: apps/v1
kind: Deployment
metadata:
  name: abctech-deploy
spec:
  selector:
    matchLabels:
      app: abctech-deploy
  replicas: 3
  template:
    metadata:
      labels:
        app: abctech-deploy
    spec:
      containers:
      - name: abctech
        image: polo5172/abctech:33
        ports:
        - containerPort: 8080

             
