apiVersion: apps/v1
kind: Deployment
metadata:
  name: abctech-deploy
spec:
  selector:
    matchLabels:
      app: abctech_deploy
  replicas: 3
  template:
    metadata:
      labels:
        app: abctech_deploy
    spec:
      containers:
      - name: abctech-app
        image: polo5172/abctech:latest
        ports:
        - containerPort: 8080

             
