apiVersion: apps/v1
kind: Deployment
metadata:
  name: abctech-deploy
spec:
  selector:
    matchLabels:
      app: abctech-app
  replicas: 3
  template:
    metadata:
      labels:
        app: abctech-app
    spec:
      containers:
      - name: abctech-container
        image: polo5172/abctech:latest
        ports:
        - containerPort: 8080

             
