apiVersion: v1
kind: Service
metadata:
  name: abtech-nodeport-svc
spec:
  selector:
    app: abctech-deploy
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort

             
