apiVersion: v1
kind: Service
metadata:
  name: abctech-nodeport-svc
spec:
  selector:
    app: abctech_deploy
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort
             
